// ====================ESTA CLASE DA ERROR YA QUE FALTA CONFIGURAR LAS CLASES EN EL PAQUETE DAO============================
package Movimiento.vista;

import Movimiento.modelo.Movimiento;
import Movimiento.modelo.Producto;
import Movimiento.modelo.Proveedor;
import Movimiento.DAO.MovimientoDAO;
import Movimiento.DAO.ProductoDAO;
import Movimiento.DAO.ProveedorDAO;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.event.*;
//import javax.swing.DefaultComboBoxModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */

public class FrmMovimiento extends javax.swing.JFrame {

    MovimientoDAO movimientoDAO = new MovimientoDAO();
    ProductoDAO productoDAO = new ProductoDAO();
    ProveedorDAO proveedorDAO = new ProveedorDAO();
    private int movimientoSeleccionadoId = -1;
    
    public FrmMovimiento() {
        initComponents();
        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>());
        setLocationRelativeTo(null);
        cargarProductos();
        cargarProveedores();
        cargarTablaMovimientos();
        cbProducto.addActionListener(e -> llenarCamposProducto());
    }
    
    private void cargarProductos(){
        cbProducto.removeAllItems();
        List<Producto> productos = productoDAO.listarProductos();
        for (Producto p : productos){
            cbProducto.addItem(p);
        }
    }
    
    private void cargarProveedores(){
        List<Proveedor> proveedores = proveedorDAO.listarProveedores();
        for (Proveedor p : proveedores){
            cbProveedor.addItem(p);
        }
    }
    
    private void llenarCamposProducto() {
        Producto seleccionado = (Producto) cbProducto.getSelectedItem();
        if (seleccionado != null) {
            txtMarca.setText(seleccionado.getMarca());
            txtModelo.setText(seleccionado.getModelo());
        }
    }
    
    private void cargarTablaMovimientos() {
        String[] columnas = {"ID", "Tipo", "Producto", "Marca", "Modelo", "Cantidad", "Costo Unitario", "Fecha", "Proveedor"};
        DefaultTableModel modeloTabla = new DefaultTableModel(null, columnas);
        List<Movimiento> lista = movimientoDAO.listarMovimientos();

        for (Movimiento m : lista) {
            modeloTabla.addRow(new Object[]{
                    m.getId(),
                    m.getTipo(),
                    m.getId_producto(),
                    m.getMarca(),
                    m.getModelo(),
                    m.getCantidad(),
                    m.getCosto_unitario(),
                    m.getFecha(),
                    m.getId_proveedor()
            });
        }
        tblMovimientos.setModel(modeloTabla);
    }
    
    private void limpiarCampos() {
        cbTipo.setSelectedIndex(0);
        cbProducto.setSelectedIndex(0);
        txtMarca.setText("");
        txtModelo.setText("");
        txtCantidad.setText("");
        txtCosto.setText("");
        txtFecha.setText("");
        movimientoSeleccionadoId = -1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        cbProducto = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbProveedor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRAR MOVIMIENTO");
        setName("frmRegistrarMovimiento"); // NOI18N

        jLabel1.setText("Formulario de Movimiento");
        jLabel1.setName("lbl1"); // NOI18N

        jLabel2.setText("Tipo de Movimiento");
        jLabel2.setName("lbl2"); // NOI18N

        jLabel3.setText("Producto");
        jLabel3.setName("lbl3"); // NOI18N

        jLabel4.setText("Cantidad");
        jLabel4.setName("lbl4"); // NOI18N

        jLabel5.setText("Costo Unitario");
        jLabel5.setName("lbl5"); // NOI18N

        jLabel6.setText("Fecha");
        jLabel6.setName("lbl6"); // NOI18N

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        cbTipo.setName("cmb1"); // NOI18N

        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbProducto.setName("cmb2"); // NOI18N

        txtCantidad.setName("txt1"); // NOI18N

        txtCosto.setName("txt2"); // NOI18N

        txtFecha.setName("txt3"); // NOI18N

        btnGuardar.setText("Guardar");
        btnGuardar.setName("btn2"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setName("btn4"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo Movimiento", "Producto", "Marca", "Modelo", "Cantidad", "Costo Unitario", "Fecha Ingreso", "Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMovimientos.setName("tbl1"); // NOI18N
        tblMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMovimientosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMovimientos);

        btnActualizar.setText("Actualizar");
        btnActualizar.setName("btn5"); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel8.setText("Marca");

        jLabel9.setText("Modelo");

        txtMarca.setEnabled(false);

        txtModelo.setEnabled(false);

        jLabel7.setText("Proveedor:");

        cbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(142, 142, 142))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel4)
                                                            .addGap(29, 29, 29)
                                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel3))
                                                    .addGap(153, 153, 153))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(28, 28, 28)))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(22, 22, 22)
                                            .addComponent(txtFecha)))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnActualizar)
                        .addGap(49, 49, 49)
                        .addComponent(btnGuardar)
                        .addGap(49, 49, 49)
                        .addComponent(btnCancelar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (movimientoSeleccionadoId == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un movimiento de la tabla para actualizar.");
            return;
        }

        try {
            Producto p = (Producto) cbProducto.getSelectedItem();
            String tipo = cbTipo.getSelectedItem().toString();
            int cantidad = Integer.parseInt(txtCantidad.getText());
            double costo = Double.parseDouble(txtCosto.getText());
            String fecha = txtFecha.getText();
            Proveedor prov = (Proveedor) cbProveedor.getSelectedItem();

            Movimiento m = new Movimiento(tipo, p.getId_producto(), p.getMarca(), p.getModelo(), cantidad, costo, fecha, prov.getId_proveedor());
            m.setId(movimientoSeleccionadoId);

            if (movimientoDAO.actualizarMovimiento(m)) {
                JOptionPane.showMessageDialog(this, "Movimiento actualizado correctamente");
                cargarTablaMovimientos();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el movimiento");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            Producto p = (Producto) cbProducto.getSelectedItem();
            String tipo = cbTipo.getSelectedItem().toString();
            int cantidad = Integer.parseInt(txtCantidad.getText());
            double costo = Double.parseDouble(txtCosto.getText());
            String fecha = txtFecha.getText();
            Proveedor prov = (Proveedor) cbProveedor.getSelectedItem();

            Movimiento m = new Movimiento(tipo, p.getId_producto(), p.getMarca(), p.getModelo(), cantidad, costo, fecha, prov.getId_proveedor());

            if (movimientoDAO.registrarMovimiento(m)) {
                JOptionPane.showMessageDialog(this, "Movimiento guardado correctamente");
                cargarTablaMovimientos();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el movimiento");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMovimientosMouseClicked
        int fila = tblMovimientos.getSelectedRow();
    if (fila >= 0) {
        movimientoSeleccionadoId = Integer.parseInt(tblMovimientos.getValueAt(fila, 0).toString());
        cbTipo.setSelectedItem(tblMovimientos.getValueAt(fila, 1).toString());
        txtMarca.setText(tblMovimientos.getValueAt(fila, 3).toString());
        txtModelo.setText(tblMovimientos.getValueAt(fila, 4).toString());
        txtCantidad.setText(tblMovimientos.getValueAt(fila, 5).toString());
        txtCosto.setText(tblMovimientos.getValueAt(fila, 6).toString());
        txtFecha.setText(tblMovimientos.getValueAt(fila, 7).toString());

        // Selecciona el producto correcto en el combo
        String nombreProducto = tblMovimientos.getValueAt(fila, 2).toString();
        for (int i = 0; i < cbProducto.getItemCount(); i++) {
            Producto prod = cbProducto.getItemAt(i);
            if (prod.getNombre().equals(nombreProducto)) {
                cbProducto.setSelectedIndex(i);
                break;
            }
        }

        // Selecciona el proveedor correcto en el combo
        String nombreProveedor = tblMovimientos.getValueAt(fila, 8).toString();
        for (int i = 0; i < cbProveedor.getItemCount(); i++) {
            Proveedor prov = cbProveedor.getItemAt(i);
            if (prov.getNombre().equals(nombreProveedor)) {
                cbProveedor.setSelectedIndex(i);
                break;
            }
        }
    }
    }//GEN-LAST:event_tblMovimientosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMovimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Producto> cbProducto;
    private javax.swing.JComboBox<Proveedor> cbProveedor;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
